name: "OWASP ZAP DAST"

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start demo app (docker)
        run: |
          docker build -t demo-app .
          docker run -d --name demo-app -p 5000:5000 demo-app
        # adapt to your Dockerfile or start step

      - name: Wait for app
        run: |
          for i in {1..10}; do curl -s http://localhost:5000 && break || sleep 2; done

      - name: Run ZAP baseline scan
        uses: zaproxy/action-baseline@v0.6.0
        with:
          target: 'http://host.docker.internal:5000' # on Linux runners use localhost
          rules_file_name: zap-rules.md

      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
